name: Flutter Docker CI/CD

on:
  push:
    branches:
      - nhathuy

  pull_request:
    branches:
      - nhathuy

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t fruit-store-builder ./fruit_store

      - name: Create Container
        run: docker create --name fruit-store-container fruit-store-builder

      - name: Copy APK
        run: |
          docker cp fruit-store-container:/app/build/app/outputs/flutter-apk/app-release.apk ./app-release.apk

      - name: Remove Container
        run: docker rm fruit-store-container

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fruit-store-apk
          path: app-release.apk
